const routes = {
  HOME: "/",
  LOGIN: "/login",
  CREATE_ACCOUNT: "/create-account",
  DIGITAL_LIBRARY: "/digital-library",
  MEMBERS: "/members",
  OPEN_DATA: "/solutions/open-data",
  D2L: "/solutions/dental-second-look",
  PERSONAL_DATA: "/profile/personal-data",
  COLLABORATORS: "/profile/collaborators",
  COLLABORATORS_ID: (id = "new") => `/profile/collaborators/${id}`,
  GROUPS: "/profile/groups",
  GROUPS_ID: (id = "new") => `/profile/groups/${id}`,
  PAPERS: "/profile/papers",
  PAPERS_ID: (id = "new") => `/profile/papers/${id}`,
  USERS: "/profile/users",
  USERS_ID: (id = "new") => `/profile/users/${id}`,
  ACCESS_REQUESTS: "/profile/access-requests",
  ACCESS_REQUESTS_ID: (id = "new") => `/profile/access-requests/${id}`,
  PROFILE_D2L: "/profile/dental-second-look",
  PROFILE_OPEN_DATA: "/profile/open-data",
  PROFILE_ACCEPT_TERMS: "/profile/accept-terms",
  PROFILE_PRIVACY_POLICY: "/profile/privacy-policy",
  MY_SOLUTIONS: "/my-solutions",
  FACEBOOK: "https://www.facebook.com/",
  INSTAGRAM: "https://www.instagram.com/",
  LINKEDIN: "https://www.linkedin.com/",
  PRIVACY_POLICY: "/privacy-policy",
  ACCEPT_TERMS: "/accept-terms",
};

export default routes;
